AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2   #dog,cat
WEIGHTS: imagenet  #weights of which dataset you want to use.imagenet is trained on 1000 classes. vgg16 is already trained on this imagenet dataset
LEARNING_RATE: 0.01